# TODO: README를 참고해 빌드 폴더, 공개 포트와 저장 경로·볼륨을 완성하세요.
name: week5hw
services:
  api:            
    build: ./api
    volumes:
      - data:/app/data
    networks:
      - week5_net

  web:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - week5_net

networks:
  week5_net:
    driver: bridge

volumes:
  data:
    name: week5_data02